import csv

data = """
20/9/25	SATURDAY	1PM	TUSKER	KCB	NYAYO STADIUM	NAIROBI
20/9/25	SATURDAY	4PM	AFC LEOPARDS	SOFAPAKA	NYAYO STADIUM	NAIROBI
21/9/25	SUNDAY	1PM	K-SHARKS	BANDARI	KASARANI ANNEX	NAIROBI
21/9/25	SUNDAY	4PM	GOR MAHIA	BIDCO UNITED	KASARANI STADIUM	NAIROBI
22/9/25	MONDAY	4PM	KK HOMEBOYZ	NAIROBI UNITED	BUKHUNGU STADIUM	KAKAMEGA
21/9/25	SUNDAY	2PM	SHABANA	APS BOMET	GUSII STADIUM	KISII
21/9/25	SUNDAY	3PM	MURANG'A SEAL	ULINZI STARS	SPORTPESA ARENA	MURANG'A
22/9/25	MONDAY	3PM	KENYA POLICE	MARA SUGAR	POLICE SACCO GROUNDS	NAIROBI
22/9/25	MONDAY	4PM	MATHARE UNITED	POSTA RANGERS	KASARANI ANNEX	NAIROBI
26/9/25	FRIDAY	1PM	KCB	MATHARE UNITED	ULINZI SPORTS COMPLEX	NAIROBI
26/9/25	FRIDAY	4PM	ULINZI STARS	K-SHARKS	ULINZI SPORTS COMPLEX	NAIROBI
27/9/25	SATURDAY	1PM	POSTA RANGERS	TUSKER	KENYATTA STADIUM	MACHAKOS
27/9/25	SATURDAY	4PM	SOFAPAKA	GOR MAHIA	KENYATTA STADIUM	MACHAKOS
27/9/25	SATURDAY	3PM	BANDARI	SHABANA	KPA SPORTS CLUB	MOMBASA
27/9/25	SATURDAY	3PM	MARA SUGAR	KK HOMEBOYZ	GREEN STADIUM	AWENDO
28/9/25	SUNDAY	3PM	APS BOMET	MURANG'A SEAL	GUSII STADIUM	KISII
29/9/25	MONDAY	3PM	NAIROBI UNITED	AFC LEOPARDS	NYAYO STADIUM	NAIROBI
30/9/25	TUESDAY	3PM	BIDCO UNITED	KENYA POLICE	KENYATTA STADIUM	MACHAKOS
30/9/25	TUESDAY	6PM	KENYA POLICE	ULINZI STARS	POLICE SACCO GROUNDS	NAIROBI
30/9/25	TUESDAY	4PM	K-SHARKS	KCB	POLICE SACCO GROUNDS	NAIROBI
1/10/2025	WEDNESDAY	4PM	TUSKER	MATHARE UNITED	KASARANI ANNEX	NAIROBI
2/10/2025	THURSDAY	3PM	MARA SUGAR	NAIROBI UNITED	GREEN STADIUM	AWENDO
15/10/25	WEDNESDAY	3PM	KK HOMEBOYZ	BIDCO UNITED	BUKHUNGU STADIUM	KAKAMEGA
15/10/25	WEDNESDAY	2PM	SHABANA	POSTA RANGERS	GUSII STADIUM	KISII
15/10/25	WEDNESDAY	3PM	MURANG'A SEAL	SOFAPAKA	SPORTPESA ARENA	MURANG'A
15/10/25	WEDNESDAY	6PM	AFC LEOPARDS	BANDARI	NYAYO STADIUM	NAIROBI
16/10/25	THURSDAY	6PM	GOR MAHIA	APS BOMET	KASARANI STADIUM	NAIROBI
3/10/2025	FRIDAY	3PM	SOFAPAKA	KK HOMEBOYZ	KASARANI ANNEX	NAIROBI
3/10/2025	FRIDAY	6PM	POSTA RANGERS	AFC LEOPARDS	NYAYO STADIUM	NAIROBI
4/10/2025	SATURDAY	3PM	BANDARI	MURANG'A SEAL	KPA SPORTS CLUB	MOMBASA
4/10/2025	SATURDAY	4PM	KCB	GOR MAHIA	NYAYO STADIUM	NAIROBI
4/10/2025	SATURDAY	3PM	APS BOMET	KENYA POLICE	GUSII STADIUM	KISII
5/10/2025	SUNDAY	2PM	MATHARE UNITED	K-SHARKS	KASARANI ANNEX	NAIROBI
5/10/2025	SUNDAY	4PM	TUSKER	SHABANA	NYAYO STADIUM	NAIROBI
6/10/2025	MONDAY	3PM	BIDCO UNITED	NAIROBI UNITED	KENYATTA STADIUM	MACHAKOS
6/10/2025	MONDAY	5PM	ULINZI STARS	MARA SUGAR	ULINZI SPORTS COMPLEX	NAIROBI
18/10/25	SATURDAY	3PM	KK HOMEBOYZ	ULINZI STARS	BUKHUNGU STADIUM	KAKAMEGA
18/10/25	SUNDAY	3PM	MARA SUGAR	BIDCO UNITED	GREEN STADIUM	AWENDO
19/10/25	SUNDAY	3PM	MURANG'A SEAL	TUSKER	SPORTPESA ARENA	MURANG'A
19/10/25	SUNDAY	4PM	AFC LEOPARDS	KCB	NYAYO STADIUM	KAKAMEGA
20/10/25	MONDAY	1PM	K-SHARKS	APS BOMET	KASARANI ANNEX	NAIROBI
20/10/25	MONDAY	4PM	GOR MAHIA	POSTA RANGERS	KASARANI STADIUM	NAIROBI
20/10/25	MONDAY	2PM	SHABANA	MATHARE UNITED	GUSII STADIUM	KISII
21/10/25	TUESDAY	2PM	NAIROBI UNITED	BANDARI	NYAYO STADIUM	NAIROBI
22/10/25	WEDNESDAY	2PM	KENYA POLICE	SOFAPAKA	POLICE SACCO GROUNDS	NAIROBI
24/10/25	FRIDAY	4PM	TUSKER	K-SHARKS	POLICE SACCO GROUNDS	NAIROBI
25/10/25	SATURDAY	4PM	MATHARE UNITED	GOR MAHIA	KASARANI STADIUM	NAIROBI
25/10/25	SATURDAY	3PM	ULINZI STARS	BIDCO UNITED	ULINZI SPORTS COMPLEX	NAIROBI
25/10/25	SATURDAY	1PM	SOFAPAKA	MARA SUGAR	KASARANI ANNEX	NAIROBI
25/10/25	SATURDAY	3PM	APS BOMET	KK HOMEBOYZ	GUSII STADIUM	KISII
26/10/25	SUNDAY	4PM	SHABANA	AFC LEOPARDS	RAILA ODINGA STADIUM	HOMABAY
26/10/25	SUNDAY	3PM	POSTA RANGERS	MURANG'A SEAL	KENYATTA STADIUM	MACHAKOS
26/10/25	SUNDAY	4PM	BANDARI	KENYA POLICE	KPA SPORTS CLUB	MOMBASA
26/10/25	SUNDAY	3PM	KCB	NAIROBI UNITED	ULINZI SPORTS COMPLEX	NAIROBI
31/10/25	FRIDAY	3PM	MARA SUGAR	BANDARI	GUSII STADIUM	KISII
31/10/25	FRIDAY	6PM	K-SHARKS	SHABANA	KASARANI STADIUM	NAIROBI
1/11/25	SATURDAY	4PM	GOR MAHIA	ULINZI STARS	KASARANI STADIUM	NAIROBI
1/11/25	SATURDAY	3PM	KK HOMEBOYZ	TUSKER	BUKHUNGU STADIUM	KAKAMEGA
1/11/25	SATURDAY	7PM	KENYA POLICE	POSTA RANGERS	POLICE SACCO GROUNDS	NAIROBI
1/11/25	SATURDAY	1PM	NAIROBI UNITED	SOFAPAKA	NYAYO STADIUM	NAIROBI
2/11/25	SUNDAY	2PM	BIDCO UNITED	APS BOMET	KENYATTA STADIUM	MACHAKOS
2/11/25	SUNDAY	4PM	AFC LEOPARDS	APS BOMET	NYAYO STADIUM	NAIROBI
2/11/25	SUNDAY	3PM	MURANG'A SEAL	KCB	SPORTPESA ARENA	MURANG'A
5/11/25	WEDNESDAY	3PM	NAIROBI UNITED	K-SHARKS	NYAYO STADIUM	NAIROBI
5/11/25	WEDNESDAY	6PM	ULINZI STARS	SHABANA	NYAYO STADIUM	NAIROBI
6/11/25	THURSDAY	3PM	BIDCO UNITED	TUSKER	KENYATTA STADIUM	MACHAKOS
6/11/25	THURSDAY	6PM	KENYA POLICE	GOR MAHIA	NYAYO STADIUM	NAIROBI
18/11/25	TUESDAY	3PM	KK HOMEBOYZ	MURANG'A SEAL	BUKHUNGU STADIUM	KAKAMEGA
18/11/25	TUESDAY	4PM	SOFAPAKA	POSTA RANGERS	KASARANI ANNEX	NAIROBI
19/11/25	WEDNESDAY	4PM	BANDARI	KCB	KPA SPORTS CLUB	MOMBASA
19/11/25	WEDNESDAY	4PM	MARA SUGAR	AFC LEOPARDS	GREEN STADIUM	AWENDO
20/11/25	THURSDAY	3PM	APS BOMET	MATHARE UNITED	GUSII STADIUM	KISII
7/11/25	FRIDAY	4PM	MATHARE UNITED	KK HOMEBOYZ	KASARANI STADIUM	NAIROBI
8/11/25	SATURDAY	4PM	AFC LEOPARDS	MURANG'A SEAL	NYAYO STADIUM	NAIROBI
8/11/25	SATURDAY	3PM	BANDARI	SOFAPAKA	KPA SPORTS CLUB	MOMBASA
8/11/25	SATURDAY	2PM	POSTA RANGERS	MARA SUGAR	KENYATTA STADIUM	MACHAKOS
9/11/25	SUNDAY	6PM	TUSKER	KENYA POLICE	KASARANI STADIUM	NAIROBI
9/11/25	SUNDAY	4PM	SHABANA	NAIROBI UNITED	GUSII STADIUM	KISII
9/11/25	SUNDAY	4PM	K-SHARKS	GOR MAHIA	KASARANI STADIUM	NAIROBI
9/11/25	SUNDAY	1PM	APS BOMET	ULINZI STARS	GUSII STADIUM	KISII
10/11/25	MONDAY	4PM	KCB	BIDCO UNITED	ULINZI SPORTS COMPLEX	NAIROBI
22/11/25	SATURDAY	4PM	GOR MAHIA	TUSKER	KASARANI STADIUM	NAIROBI
22/11/25	SATURDAY	1PM	SOFAPAKA	ULINZI STARS	KASARANI ANNEX	NAIROBI
22/11/25	SATURDAY	3PM	KK HOMEBOYZ	POSTA RANGERS	BUKHUNGU STADIUM	KAKAMEGA
23/11/25	SUNDAY	3PM	MARA SUGAR	KCB	GREEN STADIUM	AWENDO
23/11/25	SUNDAY	1PM	BIDCO UNITED	BANDARI	KENYATTA STADIUM	MACHAKOS
23/11/25	SUNDAY	4PM	K-SHARKS	AFC LEOPARDS	KASARANI STADIUM	NAIROBI
23/11/25	SUNDAY	3PM	MURANG'A SEAL	SHABANA	SPORTPESA ARENA	MURANG'A
24/11/25	MONDAY	3PM	NAIROBI UNITED	APS BOMET	NYAYO STADIUM	NAIROBI
24/11/25	MONDAY	6PM	KENYA POLICE	MATHARE UNITED	POLICE SACCO GROUNDS	NAIROBI
28/11/25	FRIDAY	2PM	BIDCO UNITED	POSTA RANGERS	KENYATTA STADIUM	MACHAKOS
28/11/25	FRIDAY	4PM	SOFAPAKA	APS BOMET	KASARANI ANNEX	NAIROBI
29/11/25	SATURDAY	4PM	KENYA POLICE	SHABANA	NYAYO STADIUM	NAIROBI
29/11/25	SATURDAY	1PM	NAIROBI UNITED	MATHARE UNITED	NYAYO STADIUM	NAIROBI
29/11/25	SATURDAY	3PM	ULINZI STARS	BANDARI	ULINZI SPORTS COMPLEX	NAIROBI
29/11/25	SATURDAY	3PM	KK HOMEBOYZ	KCB	BUKHUNGU STADIUM	KAKAMEGA
30/11/25	SUNDAY	3PM	MARA SUGAR	TUSKER	GREEN STADIUM	AWENDO
30/11/25	SUNDAY	4PM	GOR MAHIA	APS BOMET	KASARANI STADIUM	NAIROBI
30/11/25	SUNDAY	3PM	MURANG'A SEAL	K-SHARKS	SPORTPESA ARENA	MURANG'A
5/12/25	FRIDAY	4PM	POSTA RANGERS	NAIROBI UNITED	KENYATTA STADIUM	MACHAKOS
5/12/25	FRIDAY	6PM	TUSKER	ULINZI STARS	POLICE SACCO GROUNDS	NAIROBI
6/12/25	SATURDAY	1PM	MATHARE UNITED	MARA SUGAR	KASARANI ANNEX	NAIROBI
6/12/25	SATURDAY	3PM	AFC LEOPARDS	KK HOMEBOYZ	NYAYO STADIUM	NAIROBI
6/12/25	SATURDAY	3PM	SHABANA	BIDCO UNITED	GUSII STADIUM	KISII
6/12/25	SATURDAY	4PM	K-SHARKS	KENYA POLICE	KASARANI ANNEX	NAIROBI
7/12/25	SUNDAY	4PM	GOR MAHIA	MURANG'A SEAL	KASARANI STADIUM	NAIROBI
7/12/25	SUNDAY	1PM	KCB	APS BOMET	ULINZI SPORTS COMPLEX	NAIROBI
7/12/25	SUNDAY	3PM	APS BOMET	BANDARI	GUSII STADIUM	KISII
11/12/25	THURSDAY	1PM	BIDCO UNITED	MATHARE UNITED	KASARANI ANNEX	NAIROBI
11/12/25	THURSDAY	3PM	MARA SUGAR	K-SHARKS	GREEN STADIUM	AWENDO
11/12/25	THURSDAY	4PM	SOFAPAKA	TUSKER	KASARANI ANNEX	NAIROBI
12/12/25	FRIDAY	4PM	KENYA POLICE	AFC LEOPARDS	NYAYO STADIUM	NAIROBI
12/12/25	FRIDAY	3PM	BANDARI	GOR MAHIA	KPA SPORTS CLUB	MOMBASA
12/12/25	FRIDAY	1PM	NAIROBI UNITED	MURANG'A SEAL	NYAYO STADIUM	NAIROBI
12/12/25	FRIDAY	2PM	APS BOMET	POSTA RANGERS	GUSII STADIUM	KISII
12/12/25	FRIDAY	3PM	ULINZI STARS	KCB	ULINZI SPORTS COMPLEX	NAIROBI
13/12/25	SATURDAY	3PM	KK HOMEBOYZ	SHABANA	BUKHUNGU STADIUM	KAKAMEGA
15/12/25	MONDAY	1PM	K-SHARKS	BIDCO UNITED	KASARANI ANNEX	NAIROBI
15/12/25	MONDAY	4PM	MATHARE UNITED	SOFAPAKA	KASARANI ANNEX	NAIROBI
16/12/25	TUESDAY	1PM	TUSKER	NAIROBI UNITED	ULINZI SPORTS COMPLEX	NAIROBI
16/12/25	TUESDAY	4PM	AFC LEOPARDS	ULINZI STARS	NYAYO STADIUM	NAIROBI
17/12/25	WEDNESDAY	1PM	POSTA RANGERS	BANDARI	KENYATTA STADIUM	MACHAKOS
17/12/25	WEDNESDAY	3PM	SHABANA	MARA SUGAR	GUSII STADIUM	KISII
17/12/25	WEDNESDAY	4PM	KCB	APS BOMET	ULINZI SPORTS COMPLEX	NAIROBI
18/12/25	THURSDAY	3PM	MURANG'A SEAL	APS BOMET	SPORTPESA ARENA	MURANG'A
18/12/25	THURSDAY	4PM	GOR MAHIA	KK HOMEBOYZ	KASARANI STADIUM	NAIROBI
19/12/25	FRIDAY	4PM	SOFAPAKA	K-SHARKS	KASARANI ANNEX	NAIROBI
20/12/25	SATURDAY	4PM	BIDCO UNITED	AFC LEOPARDS	KENYATTA STADIUM	MACHAKOS
20/12/25	SATURDAY	3PM	ULINZI STARS	POSTA RANGERS	ULINZI SPORTS COMPLEX	NAIROBI
21/12/25	SUNDAY	3PM	BANDARI	MATHARE UNITED	KPA SPORTS CLUB	MOMBASA
21/12/25	SUNDAY	3PM	MARA SUGAR	MURANG'A SEAL	GREEN STADIUM	AWENDO
21/12/25	SUNDAY	4PM	NAIROBI UNITED	GOR MAHIA	NYAYO STADIUM	NAIROBI
21/12/25	SUNDAY	3PM	APS BOMET	TUSKER	GREEN STADIUM	AWENDO
22/12/25	MONDAY	4PM	KCB	SHABANA	NYAYO STADIUM	NAIROBI
22/12/25	MONDAY	3PM	KK HOMEBOYZ	KENYA POLICE	BUKHUNGU STADIUM	KAKAMEGA
9/1/26	FRIDAY	1PM	ULINZI STARS	NAIROBI UNITED	ULINZI SPORTS COMPLEX	NAIROBI
9/1/26	FRIDAY	4PM	KCB	KENYA POLICE	ULINZI SPORTS COMPLEX	NAIROBI
10/1/26	SATURDAY	1PM	MATHARE UNITED	MURANG'A SEAL	KASARANI STADIUM	NAIROBI
10/1/26	SATURDAY	4PM	TUSKER	AFC LEOPARDS	NYAYO STADIUM	NAIROBI
10/1/26	SATURDAY	3PM	POSTA RANGERS	K-SHARKS	KENYATTA STADIUM	MACHAKOS
10/1/26	SATURDAY	3PM	BANDARI	KK HOMEBOYZ	KPA SPORTS CLUB	MOMBASA
10/1/26	SATURDAY	3PM	SOFAPAKA	BIDCO UNITED	KASARANI ANNEX	NAIROBI
11/1/26	SUNDAY	4PM	SHABANA	GOR MAHIA	KASARANI STADIUM	NAIROBI
11/1/26	SUNDAY	3PM	APS BOMET	MARA SUGAR	GUSII STADIUM	KISII
15/1/26	THURSDAY	2PM	POSTA RANGERS	KCB	KENYATTA STADIUM	MACHAKOS
15/1/26	THURSDAY	4PM	MATHARE UNITED	ULINZI STARS	KASARANI STADIUM	NAIROBI
16/1/26	FRIDAY	3PM	TUSKER	BANDARI	POLICE SACCO GROUNDS	NAIROBI
16/1/26	FRIDAY	6PM	KENYA POLICE	NAIROBI UNITED	POLICE SACCO GROUNDS	NAIROBI
17/1/26	SATURDAY	1PM	K-SHARKS	KK HOMEBOYZ	KASARANI ANNEX	NAIROBI
17/1/26	SATURDAY	4PM	AFC LEOPARDS	APS BOMET	NYAYO STADIUM	NAIROBI
17/1/26	SATURDAY	3PM	SHABANA	SOFAPAKA	GUSII STADIUM	KISII
18/1/26	SUNDAY	4PM	GOR MAHIA	MARA SUGAR	KASARANI STADIUM	NAIROBI
18/1/26	SUNDAY	3PM	MURANG'A SEAL	BIDCO UNITED	SPORTPESA ARENA	MURANG'A
20/1/26	TUESDAY	3PM	POSTA RANGERS	MATHARE UNITED	KENYATTA STADIUM	MACHAKOS
20/1/26	TUESDAY	4PM	KCB	TUSKER	ULINZI SPORTS COMPLEX	NAIROBI
20/1/26	TUESDAY	1PM	NAIROBI UNITED	KK HOMEBOYZ	NYAYO STADIUM	NAIROBI
21/1/26	WEDNESDAY	3PM	APS BOMET	SHABANA	GUSII STADIUM	KISII
27/1/26	TUESDAY	3PM	BIDCO UNITED	GOR MAHIA	KENYATTA STADIUM	MACHAKOS
28/1/26	WEDNESDAY	3PM	BANDARI	K-SHARKS	KPA SPORTS CLUB	MOMBASA
28/1/26	WEDNESDAY	3PM	MARA SUGAR	KENYA POLICE	GREEN STADIUM	AWENDO
28/1/26	WEDNESDAY	4PM	SOFAPAKA	AFC LEOPARDS	KASARANI STADIUM	NAIROBI
29/1/26	THURSDAY	3PM	ULINZI STARS	MURANG'A SEAL	ULINZI SPORTS COMPLEX	NAIROBI
23/1/26	FRIDAY	3PM	K-SHARKS	ULINZI STARS	KASARANI ANNEX	NAIROBI
23/1/26	FRIDAY	6PM	KENYA POLICE	BIDCO UNITED	POLICE SACCO GROUNDS	NAIROBI
24/1/26	SATURDAY	3PM	TUSKER	POSTA RANGERS	POLICE SACCO GROUNDS	NAIROBI
24/1/26	SATURDAY	1PM	MATHARE UNITED	KCB	KASARANI STADIUM	NAIROBI
24/1/26	SATURDAY	3PM	KK HOMEBOYZ	MARA SUGAR	BUKHUNGU STADIUM	KAKAMEGA
24/1/26	SATURDAY	3PM	SHABANA	BANDARI	GUSII STADIUM	KISII
24/1/26	SATURDAY	4PM	GOR MAHIA	SOFAPAKA	KASARANI STADIUM	NAIROBI
25/1/26	SUNDAY	4PM	AFC LEOPARDS	NAIROBI UNITED	NYAYO STADIUM	NAIROBI
25/1/26	SUNDAY	3PM	MURANG'A SEAL	APS BOMET	SPORTPESA ARENA	MURANG'A
6/2/26	FRIDAY	4PM	MATHARE UNITED	TUSKER	KASARANI STADIUM	NAIROBI
7/2/26	SATURDAY	1PM	BIDCO UNITED	KK HOMEBOYZ	KENYATTA STADIUM	MACHAKOS
7/2/26	SATURDAY	4PM	POSTA RANGERS	SHABANA	KENYATTA STADIUM	MACHAKOS
7/2/26	SATURDAY	3PM	BANDARI	AFC LEOPARDS	KPA SPORTS CLUB	MOMBASA
8/2/26	SUNDAY	4PM	ULINZI STARS	KENYA POLICE	ULINZI SPORTS COMPLEX	NAIROBI
8/2/26	SUNDAY	3PM	SOFAPAKA	MURANG'A SEAL	KASARANI ANNEX	NAIROBI
8/2/26	SUNDAY	1PM	KCB	K-SHARKS	ULINZI SPORTS COMPLEX	NAIROBI
8/2/26	SUNDAY	3PM	APS BOMET	GOR MAHIA	GUSII STADIUM	KISII
9/2/26	MONDAY	4PM	NAIROBI UNITED	MARA SUGAR	NYAYO STADIUM	NAIROBI
13/2/26	FRIDAY	4PM	K-SHARKS	TUSKER	KASARANI ANNEX	NAIROBI
13/2/26	FRIDAY	1PM	BIDCO UNITED	ULINZI STARS	KENYATTA STADIUM	MACHAKOS
14/2/26	SATURDAY	4PM	GOR MAHIA	MATHARE UNITED	KASARANI STADIUM	NAIROBI
14/2/26	SATURDAY	3PM	MARA SUGAR	SOFAPAKA	GREEN STADIUM	AWENDO
14/2/26	SATURDAY	1PM	KENYA POLICE	BANDARI	POLICE SACCO GROUNDS	NAIROBI
14/2/26	SATURDAY	3PM	NAIROBI UNITED	KCB	NYAYO STADIUM	NAIROBI
15/2/26	SUNDAY	3PM	MURANG'A SEAL	POSTA RANGERS	SPORTPESA ARENA	MURANG'A
15/2/26	SUNDAY	4PM	AFC LEOPARDS	APS BOMET	NYAYO STADIUM	NAIROBI
15/2/26	SUNDAY	3PM	KK HOMEBOYZ	APS BOMET	BUKHUNGU STADIUM	KAKAMEGA
18/2/26	WEDNESDAY	3PM	ULINZI STARS	KK HOMEBOYZ	ULINZI SPORTS COMPLEX	NAIROBI
18/2/26	WEDNESDAY	6PM	MATHARE UNITED	SHABANA	KASARANI STADIUM	NAIROBI
18/2/26	WEDNESDAY	3PM	SOFAPAKA	KENYA POLICE	KASARANI ANNEX	NAIROBI
19/2/26	THURSDAY	4PM	KCB	AFC LEOPARDS	ULINZI SPORTS COMPLEX	NAIROBI
19/2/26	THURSDAY	3PM	APS BOMET	K-SHARKS	GUSII STADIUM	KISII
24/2/26	TUESDAY	4PM	POSTA RANGERS	GOR MAHIA	KENYATTA STADIUM	MACHAKOS
24/2/26	TUESDAY	3PM	BANDARI	NAIROBI UNITED	KPA SPORTS CLUB	MOMBASA
25/2/26	WEDNESDAY	3PM	TUSKER	MURANG'A SEAL	ULINZI SPORTS COMPLEX	NAIROBI
25/2/26	WEDNESDAY	3PM	BIDCO UNITED	MARA SUGAR	KENYATTA STADIUM	MACHAKOS
27/2/26	FRIDAY	4PM	K-SHARKS	MATHARE UNITED	KASARANI ANNEX	NAIROBI
28/2/26	SATURDAY	4PM	AFC LEOPARDS	POSTA RANGERS	NYAYO STADIUM	NAIROBI
28/2/26	SATURDAY	3PM	KK HOMEBOYZ	SOFAPAKA	BUKHUNGU STADIUM	KAKAMEGA
28/2/26	SATURDAY	3PM	KENYA POLICE	APS BOMET	POLICE SACCO GROUNDS	NAIROBI
1/3/26	SUNDAY	4PM	GOR MAHIA	KCB	KASARANI STADIUM	NAIROBI
1/3/26	SUNDAY	3PM	SHABANA	TUSKER	GUSII STADIUM	KISII
1/3/26	SUNDAY	3PM	MURANG'A SEAL	BANDARI	SPORTPESA ARENA	MURANG'A
2/3/26	MONDAY	4PM	NAIROBI UNITED	BIDCO UNITED	NYAYO STADIUM	NAIROBI
2/3/26	MONDAY	3PM	MARA SUGAR	ULINZI STARS	GREEN STADIUM	AWENDO
6/3/26	FRIDAY	4PM	SOFAPAKA	NAIROBI UNITED	KASARANI ANNEX	NAIROBI
7/3/26	SATURDAY	4PM	ULINZI STARS	GOR MAHIA	ULINZI SPORTS COMPLEX	NAIROBI
7/3/26	SATURDAY	3PM	POSTA RANGERS	KENYA POLICE	KENYATTA STADIUM	MACHAKOS
7/3/26	SATURDAY	3PM	SHABANA	K-SHARKS	GUSII STADIUM	KISII
7/3/26	SATURDAY	1PM	KCB	MURANG'A SEAL	ULINZI SPORTS COMPLEX	NAIROBI
8/3/26	SUNDAY	3PM	BANDARI	MARA SUGAR	KPA SPORTS CLUB	MOMBASA
8/3/26	SUNDAY	1PM	TUSKER	KK HOMEBOYZ	POLICE SACCO GROUNDS	NAIROBI
8/3/26	SUNDAY	4PM	MATHARE UNITED	AFC LEOPARDS	KASARANI STADIUM	NAIROBI
8/3/26	SUNDAY	3PM	APS BOMET	BIDCO UNITED	GUSII STADIUM	KISII
12/3/26	THURSDAY	4PM	K-SHARKS	POSTA RANGERS	KASARANI ANNEX	NAIROBI
13/3/26	FRIDAY	4PM	KENYA POLICE	KCB	POLICE SACCO GROUNDS	NAIROBI
13/3/26	FRIDAY	6PM	NAIROBI UNITED	ULINZI STARS	NYAYO STADIUM	NAIROBI
13/3/26	FRIDAY	2PM	BIDCO UNITED	SOFAPAKA	KENYATTA STADIUM	NAIROBI
13/3/26	FRIDAY	3PM	KK HOMEBOYZ	BANDARI	BUKHUNGU STADIUM	KAKAMEGA
14/3/26	SATURDAY	4PM	AFC LEOPARDS	TUSKER	NYAYO STADIUM	NAIROBI
14/3/26	SATURDAY	3PM	MARA SUGAR	APS BOMET	GREEN STADIUM	AWENDO
15/3/26	SUNDAY	4PM	GOR MAHIA	SHABANA	KASARANI STADIUM	NAIROBI
15/3/26	SUNDAY	3PM	MURANG'A SEAL	MATHARE UNITED	SPORTPESA ARENA	MURANG'A
17/3/26	TUESDAY	4PM	ULINZI STARS	SOFAPAKA	ULINZI SPORTS COMPLEX	NAIROBI
17/3/26	TUESDAY	3PM	POSTA RANGERS	KK HOMEBOYZ	KENYATTA STADIUM	MACHAKOS
18/3/26	WEDNESDAY	4PM	APS BOMET	NAIROBI UNITED	GUSII STADIUM	KISII
18/3/26	WEDNESDAY	6PM	AFC LEOPARDS	K-SHARKS	NYAYO STADIUM	NAIROBI
18/3/26	WEDNESDAY	3PM	KCB	MARA SUGAR	ULINZI SPORTS COMPLEX	NAIROBI
18/3/26	WEDNESDAY	3PM	BANDARI	BIDCO UNITED	KPA SPORTS CLUB	MOMBASA
19/3/26	THURSDAY	6PM	TUSKER	GOR MAHIA	KASARANI STADIUM	NAIROBI
19/3/26	THURSDAY	4PM	SHABANA	MURANG'A SEAL	GUSII STADIUM	KISII
19/3/26	THURSDAY	6PM	MATHARE UNITED	KENYA POLICE	KASARANI STADIUM	NAIROBI
3/4/26	FRIDAY	6PM	KENYA POLICE	TUSKER	POLICE SACCO GROUNDS	NAIROBI
4/4/26	SATURDAY	4PM	GOR MAHIA	K-SHARKS	KASARANI STADIUM	NAIROBI
4/4/26	SATURDAY	3PM	MARA SUGAR	POSTA RANGERS	GREEN STADIUM	AWENDO
4/4/26	SATURDAY	1PM	ULINZI STARS	APS BOMET	ULINZI SPORTS COMPLEX	NAIROBI
5/4/26	SUNDAY	3PM	KK HOMEBOYZ	MATHARE UNITED	BUKHUNGU STADIUM	KAKAMEGA
5/4/26	SUNDAY	3PM	MURANG'A SEAL	AFC LEOPARDS	SPORTPESA ARENA	MURANG'A
5/4/26	SUNDAY	1PM	SOFAPAKA	BANDARI	KASARANI ANNEX	NAIROBI
5/4/26	SUNDAY	4PM	NAIROBI UNITED	SHABANA	NYAYO STADIUM	NAIROBI
6/4/26	MONDAY	4PM	BIDCO UNITED	KCB	KENYATTA STADIUM	MACHAKOS
10/4/26	FRIDAY	4PM	MATHARE UNITED	BIDCO UNITED	KASARANI STADIUM	NAIROBI
11/4/26	SATURDAY	4PM	GOR MAHIA	BANDARI	KASARANI STADIUM	NAIROBI
11/4/26	SATURDAY	1PM	TUSKER	SOFAPAKA	POLICE SACCO GROUNDS	NAIROBI
11/4/26	SATURDAY	3PM	SHABANA	KK HOMEBOYZ	GUSII STADIUM	KISII
12/4/26	SUNDAY	3PM	POSTA RANGERS	APS BOMET	KENYATTA STADIUM	MACHAKOS
12/4/26	SUNDAY	4PM	AFC LEOPARDS	KENYA POLICE	NYAYO STADIUM	NAIROBI
12/4/26	SUNDAY	1PM	K-SHARKS	MARA SUGAR	KASARANI ANNEX	NAIROBI
12/4/26	SUNDAY	3PM	MURANG'A SEAL	APS BOMET	SPORTPESA ARENA	MURANG'A
13/4/26	MONDAY	4PM	KCB	ULINZI STARS	ULINZI SPORTS COMPLEX	NAIROBI
17/4/26	FRIDAY	6PM	NAIROBI UNITED	TUSKER	NYAYO STADIUM	NAIROBI
18/4/26	SATURDAY	3PM	KK HOMEBOYZ	GOR MAHIA	BUKHUNGU STADIUM	KAKAMEGA
18/4/26	SATURDAY	1PM	BIDCO UNITED	K-SHARKS	KENYATTA STADIUM	MACHAKOS
18/4/26	SATURDAY	3PM	BANDARI	POSTA RANGERS	KPA SPORTS CLUB	MOMBASA
18/4/26	SATURDAY	4PM	KENYA POLICE	MURANG'A SEAL	POLICE SACCO GROUNDS	NAIROBI
19/4/26	SUNDAY	4PM	ULINZI STARS	AFC LEOPARDS	ULINZI SPORTS COMPLEX	NAIROBI
19/4/26	SUNDAY	3PM	MARA SUGAR	SHABANA	GREEN STADIUM	AWENDO
19/4/26	SUNDAY	1PM	SOFAPAKA	MATHARE UNITED	KASARANI ANNEX	NAIROBI
20/4/26	MONDAY	3PM	APS BOMET	KCB	GUSII STADIUM	KISII
24/4/26	FRIDAY	4PM	KCB	KK HOMEBOYZ	ULINZI SPORTS COMPLEX	NAIROBI
25/4/26	SATURDAY	4PM	MATHARE UNITED	NAIROBI UNITED	KASARANI STADIUM	NAIROBI
25/4/26	SATURDAY	4PM	TUSKER	MARA SUGAR	POLICE SACCO GROUNDS	NAIROBI
25/4/26	SATURDAY	3PM	BANDARI	ULINZI STARS	KPA SPORTS CLUB	MOMBASA
25/4/26	SATURDAY	3PM	SHABANA	KENYA POLICE	GUSII STADIUM	KISII
25/4/26	SATURDAY	1PM	K-SHARKS	MURANG'A SEAL	KASARANI ANNEX	NAIROBI
26/4/26	SUNDAY	3PM	APS BOMET	SOFAPAKA	GUSII STADIUM	KISII
26/4/26	SUNDAY	4PM	AFC LEOPARDS	GOR MAHIA	NYAYO STADIUM	NAIROBI
27/4/26	MONDAY	4PM	POSTA RANGERS	BIDCO UNITED	KENYATTA STADIUM	MACHAKOS
1/5/26	FRIDAY	4PM	KENYA POLICE	K-SHARKS	POLICE SACCO GROUNDS	NAIROBI
2/5/26	SATURDAY	3PM	BANDARI	APS BOMET	KPA SPORTS CLUB	MOMBASA
2/5/26	SATURDAY	3PM	MARA SUGAR	MATHARE UNITED	GREEN STADIUM	AWENDO
2/5/26	SATURDAY	3PM	KK HOMEBOYZ	AFC LEOPARDS	BUKHUNGU STADIUM	KAKAMEGA
2/5/26	SATURDAY	4PM	BIDCO UNITED	SHABANA	KENYATTA STADIUM	MACHAKOS
2/5/26	SATURDAY	1PM	ULINZI STARS	TUSKER	ULINZI SPORTS COMPLEX	NAIROBI
3/5/26	SUNDAY	1PM	SOFAPAKA	KCB	KASARANI ANNEX	NAIROBI
3/5/26	SUNDAY	4PM	MURANG'A SEAL	GOR MAHIA	SPORTPESA ARENA	MURANG'A
3/5/26	SUNDAY	3PM	NAIROBI UNITED	POSTA RANGERS	NYAYO STADIUM	NAIROBI
8/5/26	FRIDAY	2PM	KCB	BANDARI	ULINZI SPORTS COMPLEX	NAIROBI
9/5/26	SATURDAY	4PM	K-SHARKS	NAIROBI UNITED	KASARANI ANNEX	NAIROBI
9/5/26	SATURDAY	1PM	MATHARE UNITED	APS BOMET	KASARANI STADIUM	NAIROBI
9/5/26	SATURDAY	4PM	AFC LEOPARDS	MARA SUGAR	NYAYO STADIUM	NAIROBI
9/5/26	SATURDAY	3PM	SHABANA	ULINZI STARS	GUSII STADIUM	KISII
10/5/26	SUNDAY	4PM	GOR MAHIA	KENYA POLICE	KASARANI STADIUM	NAIROBI
10/5/26	SUNDAY	1PM	TUSKER	BIDCO UNITED	POLICE SACCO GROUNDS	NAIROBI
10/5/26	SUNDAY	3PM	MURANG'A SEAL	KK HOMEBOYZ	SPORTPESA ARENA	MURANG'A
11/5/26	MONDAY	3PM	POSTA RANGERS	SOFAPAKA	KENYATTA STADIUM	MACHAKOS
16/5/26	SATURDAY	3PM	BANDARI	TUSKER	KPA SPORTS CLUB	MOMBASA
16/5/26	SATURDAY	3PM	ULINZI STARS	MATHARE UNITED	ULINZI SPORTS COMPLEX	NAIROBI
16/5/26	SATURDAY	3PM	KK HOMEBOYZ	K-SHARKS	BUKHUNGU STADIUM	KAKAMEGA
16/5/26	SATURDAY	3PM	BIDCO UNITED	MURANG'A SEAL	KENYATTA STADIUM	MACHAKOS
16/5/26	SATURDAY	3PM	MARA SUGAR	GOR MAHIA	GREEN STADIUM	AWENDO
16/5/26	SATURDAY	3PM	SOFAPAKA	SHABANA	KASARANI ANNEX	NAIROBI
16/5/26	SATURDAY	3PM	KCB	POSTA RANGERS	SPORTPESA ARENA	MURANG'A
16/5/26	SATURDAY	3PM	APS BOMET	AFC LEOPARDS	GUSII STADIUM	KISII
16/5/26	SATURDAY	3PM	NAIROBI UNITED	KENYA POLICE	NYAYO STADIUM	NAIROBI
30/5/26	SATURDAY	3PM	GOR MAHIA	NAIROBI UNITED	KASARANI STADIUM	NAIROBI
30/5/26	SATURDAY	3PM	TUSKER	APS BOMET	ULINZI SPORTS COMPLEX	NAIROBI
30/5/26	SATURDAY	3PM	MATHARE UNITED	BANDARI	KASARANI ANNEX	NAIROBI
30/5/26	SATURDAY	3PM	AFC LEOPARDS	BIDCO UNITED	NYAYO STADIUM	NAIROBI
30/5/26	SATURDAY	3PM	POSTA RANGERS	ULINZI STARS	KENYATTA STADIUM	MACHAKOS
30/5/26	SATURDAY	3PM	SHABANA	KCB	GUSII STADIUM	KISII
30/5/26	SATURDAY	3PM	K-SHARKS	SOFAPAKA	KASARANI ANNEX	NAIROBI
30/5/26	SATURDAY	3PM	MURANG'A SEAL	MARA SUGAR	SPORTPESA ARENA	MURANG'A
30/5/26	SATURDAY	3PM	KENYA POLICE	KK HOMEBOYZ	POLICE SACCO GROUNDS	NAIROBI

"""  # You can add all your fixtures here

lines = data.strip().split('\n')

with open('fixtures.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['Date', 'Day', 'Time', 'Home', 'Away', 'Stadium', 'City'])
    for line in lines:
        writer.writerow(line.split('\t'))

print("fixtures.csv has been created in the current folder.")
